version: '3.1'

services:
  app:
    build: .
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DEBUG=false

      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /var/lib/postgresql/data